---
- name: install packages to allow apt to use a repository over HTTPS.
  apt:
    name: ['ca-certificates', 'curl', 'gnupg', 'lsb-release']
    state: present

- name: Get Docker repository key.
  shell:
    cmd: "curl -fsSL {{docker['repo']['url']}}/{{docker['repo']['key']}} | gpg --yes --dearmor -o /usr/share/keyrings/docker.gpg"

- name: Add Docker apt repository.
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/docker.gpg] {{docker['repo']['url']}} {{ansible_lsb['codename']}} stable"
    state: present
    filename: docker
